image: docker:19.03

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk update && apk add bash
    - chmod +x ./docker/dockerize.sh
  script:
    - ./docker/dockerize.sh build
    - ./docker/dockerize.sh push
    - ./docker/dockerize.sh clean
  only:
    - dev
    - master



