version: "3.4"

services:
  db:
    restart: always
    image: postgres:15.3-alpine
    container_name: fastapi_starter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_DB: database
    ports:
      - "6432:5432"

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: fastapi_starter_backend
    command: ./docker/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    restart: always
    volumes:
      - ./src:/opt/app/src
